### PR TITLE
Fixes and ideas for the readme

### PR DESCRIPTION
**Pull request by kataklys**
English isn't my native language either, but I might be able to help here and there...

I have a few FIXMEEE comments in the example configuration file, things that I personally felt the need to see explained when I read the file and used the extension. If you agree with them (and maybe explain to me the inner workings of some of them) I can write the rest of the text.

### CODE REVIEW

**Comment by liximomo** [comment]
Thank you so much! 😘 

> // FIXMEEEEEEE: creating/deleting a file locally in vscode doesn't automatically make changes on the server unless the watcher is on? New files get created on either side only when syncing to that side and using syncMode full. Same with deletions.
This option only in relation to how `Sync to remote` or `Sync to local` works. 'update' means that it only affects files exist in both remote and local. 'full' means not only existing files but also created files or deleted files will be synchronized.

// FIXMEEE what's the difference between Download and Sync to local? And between Upload and Sync to remote?
The download is a copy operation. And I think it's clear how sync works that I explained in above question. I will give you a more detail example.
```
source-dir
   |- s1.txt
dest-dir
    |-d1.txt
    |-d2.txt
```
When you download `source-dir ` to `dest-dir` the `dest-dir` will be
```
dest-dir
    |-d1.txt
    |-d2.txt
    |-s1.txt
```

Back to starting point. When you sync `source-dir ` to `dest-dir` with  `syncMode: 'update'`. Nothing changes, because there are no files in common.
```
source-dir
   |- s1.txt
dest-dir
    |-d1.txt
    |-d2.txt
```

when you sync `source-dir ` to `dest-dir` with  `syncMode: 'full'`.
```
source-dir
   |- s1.txt
dest-dir
    |-s1.txt
```
The two directory will be exactly same.

**Comment by liximomo** [comment]
> // FIXMEEE what's the difference between Download and Sync to local? And between Upload and Sync to remote?

The download is a copy operation. And I think it's clear how sync works that I explained in above question. I will give you a more detail example.
```
source-dir
   |- s1.txt
dest-dir
    |-d1.txt
    |-d2.txt
```
When you download `source-dir ` to `dest-dir` the `dest-dir` will be
```
dest-dir
    |-d1.txt
    |-d2.txt
    |-s1.txt
```

Back to starting point. When you sync `source-dir ` to `dest-dir` with  `syncMode: 'update'`. Nothing changes, because there are no files in common.
```
source-dir
   |- s1.txt
dest-dir
    |-d1.txt
    |-d2.txt
```

when you sync `source-dir ` to `dest-dir` with  `syncMode: 'full'`.
```
source-dir
   |- s1.txt
dest-dir
    |-s1.txt
```
The two directory will be exactly same.

**Comment by liximomo** [comment]
> FIXMEEEEEEE explain the ** - what does it mean, when to put it and when not
> ```**/.vscode/**```,

`**/.vscode` means every  file or directory with name `.vscode`.
```
'a/b/.vscode' match
'a/b/.vscode/c.txt' mismatch
```

`**/.vscode/**` means every file or directory under a `.vscode` directory.
```
'a/b/.vscode/c.txt' match
'a/b/.vscode/c/d.txt' match
'a/b/.vscode/e' match
```

**Comment by liximomo** [comment]
> FIXMEEEEEEE: same logic means it *ignores* files that match the pattern, or *selects* files that match the pattern?

It means *selects* files that match the pattern? The "same" means how the pattern works is same.

> FIXMEEEEEEE the value of files is not an array like in ignore, but a string!

Yes! A glob string.

**Comment by liximomo** [comment]
I wish I've made it clear.

**Comment by kataklys** [comment]
That's great info! Everything is much clearer.
A few more questions before I get to work and integrate all the information:
1. (just to make sure that I understood correctly) So, if the remote and local dir contain the same files, `Sync to local` behaves just like `Download`?
2. When downloading, uploading and syncing, does your extension do any kind of check for the differences between files, or it just copies them from one side to the other, overwriting the destination?

And now for the big question. I see several ways of integrating this into the readme:
1. adding the necessary comments in the example config file. It will make it more verbose, but all the necessary information will be there
2.adding some of the clarifications in the example config file and some of them outside. For instance, I would modify the table that lists the commands and either put a more detailed description for each, or create a third column with a verbose description of what each command does
3. removing the details from the example config file and creating an FAQ at the end of the readme, which contains clarifications: how the local and remote path relate (we take this info out of the example config file), how sync/upload/download work etc. In this case, the example config file will be thinner, and it will only refer the FAQ a few times instead of having large comments

Which solution do you prefer?

**Comment by liximomo** [comment]
> if the remote and local dir contain the same files, `Sync to local` behaves just like `Download`?
`Sync to local` is equal to `download` only when the local and remote dir are exactly same.

```
// syncMode: 'update'
source-dir
   |- s1.txt
   |- s2.txt
dest-dir
    |-s1.txt
    |-d1.txt

// after sync to dest
dest-dir
    |-s1.txt
    |-d1.txt

// after download to dest
dest-dir
    |-s1.txt
    |- s2.txt
    |-d1.txt
```

> When downloading, uploading and syncing, does your extension do any kind of check for the differences between files, or it just copies them from one side to the other, overwriting the destination?

It just overwrites the destination?

---

I will prefer the way 2.

**Comment by liximomo** [comment]
@kataklys Could you replace the FIXMEEE with some description? Then I will merge this PR.

**Comment by kataklys** [comment]
Ok...the literary masterpiece is ready :-) Or at least close to that.
Please tell me what you think.

**Comment by kataklys** [comment]
oops, clicked on the wrong button...good thing I'm not in charge of nuclear missiles :boom:

**Comment by liximomo** [comment]
👍 👍 👍 Great job!  Thanks for your contribution!

**Comment by kataklys** [comment]
Found a typo, fixed it.
And there's one more thing: under glossary you have two extra "config root" lines (the ones in bold) - what's with those? Is it ok to delete them?

**Comment by liximomo** [comment]
I've already deleted the two lines of extra 'config root'.  😝

**Comment by kataklys** [comment]
Ok, then please fix the typo too :-) Somewhere in the table containing the commands and their explanation it says "soides" instead of "sides". See my last commit.

**Comment by liximomo** [comment]
Done! 😏

**Comment by kataklys** [comment]
Great! I hope it will help people who, like myself, want to understand in depth how this extension works before they use it on sensitive data.

Cheers! :wink:

**Pull request merged**
